"""Add Conversation and Message models and extend User

Revision ID: 9f306bcf8aba
Revises: b0869fec7ba3
Create Date: 2026-08-28 21:17:00.773801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f306bcf8aba'
down_revision: Union[str, Sequence[str], None] = 'b0869fec7ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('hitl_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('invocation_fingerprint', sa.String(), nullable=False),
    sa.Column('plan_fingerprint', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_hitl_requests_invocation_fingerprint'), 'hitl_requests', ['invocation_fingerprint'], unique=False)
    op.create_index(op.f('ix_hitl_requests_job_id'), 'hitl_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_hitl_requests_plan_fingerprint'), 'hitl_requests', ['plan_fingerprint'], unique=False)
    op.create_index(op.f('ix_hitl_requests_run_id'), 'hitl_requests', ['run_id'], unique=False)
    op.create_index(op.f('ix_hitl_requests_status'), 'hitl_requests', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['conversations.chat_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_job_id'), 'messages', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_job_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hitl_requests_status'), table_name='hitl_requests')
    op.drop_index(op.f('ix_hitl_requests_run_id'), table_name='hitl_requests')
    op.drop_index(op.f('ix_hitl_requests_plan_fingerprint'), table_name='hitl_requests')
    op.drop_index(op.f('ix_hitl_requests_job_id'), table_name='hitl_requests')
    op.drop_index(op.f('ix_hitl_requests_invocation_fingerprint'), table_name='hitl_requests')
    op.drop_table('hitl_requests')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
