"""phase_7_8_distributed

Revision ID: decf54fe137e
Revises: 882ebba1a630
Create Date: 2026-08-12 16:08:34.099211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decf54fe137e'
down_revision: Union[str, Sequence[str], None] = '882ebba1a630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_jobs_worker_id'), 'jobs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_worker_id'), table_name='jobs')
    op.drop_column('jobs', 'attempt_count')
    op.drop_column('jobs', 'heartbeat_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'worker_id')
    # ### end Alembic commands ###
